src/DevDe.UI.AppModel/Models/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevDe.UI.AppModel.Models
{
    public class Order
    {
        public Guid Id { get; set; }

        public Order()
        {
            Id = Guid.NewGuid();
        }
    }
}

src/DevDe.UI.AppModel/Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevDe.UI.AppModel.Models
{
    public class Student
    {
        public Student()
        {
            Id = Guid.NewGuid();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public DateTime BirthDate { get; set; }
    }
}

src/DevDe.UI.AppModel/Areas/Products/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevDe.UI.AppModel.Areas.Products.Controllers
{
    [Area("Products")]
    public class RegisterController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Search()
        {
            return View();
        }
    }
}

src/DevDe.UI.AppModel/Areas/Sales/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevDe.UI.AppModel.Areas.Sales.Controllers
{
    public class OrderController : Controller
    {
        [Area("Sales")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/DevDe.UI.AppModel/Controllers/HomeController.cs
using DevDe.UI.AppModel.Data;
using DevDe.UI.AppModel.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevDe.UI.AppModel.Controllers
{
    public class HomeController : Controller
    {
        //private readonly IOrderRepository _orderRepository;

        //public HomeController(IOrderRepository orderRepository)
        //{
        //    _orderRepository = orderRepository;
        //}

        public OperationService OperationService { get; }
        public OperationService OperationService2 { get; set; }

        public HomeController(OperationService operationService, OperationService operationService2)
        {
            OperationService = operationService;
            OperationService2 = operationService2;
        }

        public string Index()
        {
            //var order = _orderRepository.GetOrder();

            return 
                "First Instance: " + Environment.NewLine +
                OperationService.Transient.OperationId + Environment.NewLine +
                OperationService.Scoped.OperationId + Environment.NewLine +
                OperationService.Singleton.OperationId + Environment.NewLine +
                OperationService.SingletonInstance.OperationId + Environment.NewLine +

                Environment.NewLine +
                Environment.NewLine +

                "Second Instance: " + Environment.NewLine +
                OperationService2.Transient.OperationId + Environment.NewLine +
                OperationService2.Scoped.OperationId + Environment.NewLine +
                OperationService2.Singleton.OperationId + Environment.NewLine +
                OperationService2.SingletonInstance.OperationId + Environment.NewLine;

        }
    }
}

src/DevDe.UI.AppModel/Areas/Products/Views/Register/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Products Register!</h1>

src/DevDe.UI.AppModel/Areas/Products/Views/Register/Search.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>
    Search for products
</h1>

src/DevDe.UI.AppModel/Areas/Sales/Views/Order/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Orders Index</h1>

src/DevDe.UI.AppModel/Views/Home/Index.cshtml
@using DevDe.UI.AppModel.Data
@inject IOrderRepository OrderRepository

Ola, My name is Esdras Costa.

@OrderRepository.GetOrder().Id

src/DevDe.UI.AppModel/Views/Shared/_Layout.cshtml
<html>
<head>
    <title>@ViewData["title"] - My App Model</title>

    <environment include="Development">
        <link href="~/css/site_bundle.min.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstráp/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/css/bootstrap.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
        <link href="~/css/site.css" rel="stylesheet" />
    </environment>

    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />

</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppModel</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>

                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Products" asp-controller="Register" asp-action="Index">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Products" asp-controller="Register" asp-action="Search">Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Sales" asp-controller="Order" asp-action="Index">Order Index</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Development by Esdras Costa (<email email-domain="gmail.com">support</email> - <email>esdras.cts</email>).
        </div>
    </footer>

    <environment include="Development">
        <script src="~/js/site_bundle.min.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/jquery.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstráp/4.1.3/css/bootstrap.bundle.min.css"
                asp-fallback-src="~/lib/bootstrap/js/bootstrap.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && windows.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPnRO1LBk8lJ/PR7CA4=">
        </script>
        <script src="~/js/site.js"></script>
    </environment>

</body>
</html>